version: '3'
services:

  sign-in-service:
    build: .
    network_mode: bridge
    container_name: service_save_postgres
    expose:
      - 8088
 #     - 5432
    ports:
      - 8081:8081
      - 8088:8088
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
#    networks:
#      - serviseappnetwork

  db:
    image: library/postgres:13-alpine
    network_mode: bridge
    container_name: db
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    expose:
#      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: unless-stopped
 #   networks:
 #     - serviseappnetwork

#networks:
#    serviseappnetwork:
#      driver: bridge
#volumes:
#  postgres-data: